#!/usr/bin/env python3
"""One-shot: export sources/Pixelspace.svg → sources/glyphs.txt.

Reads the existing SVG-font source via build_font.parse_svg_font(), then
emits the canonical bitmap format consumed by tools/parse_bitmap.py.

After this migration, glyphs.txt is the canonical source. The SVG can be
regenerated from it via tools/bitmap_to_svg.py and stays around as a
versioned artifact for SVG-font-aware tooling and clean diff review.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_font import parse_svg_font  # noqa: E402
from parse_bitmap import (  # noqa: E402
    COLS, PIXEL, ROWS_ABOVE_BASELINE, ROWS_TOTAL,
)

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "sources" / "Pixelspace.svg"
DST = ROOT / "sources" / "glyphs.txt"


def pixels_to_bitmap(pixels: list[tuple[int, int]], gname: str) -> list[str]:
    grid = [["."] * COLS for _ in range(ROWS_TOTAL)]
    for x, y in pixels:
        if x % PIXEL or y % PIXEL:
            raise SystemExit(
                f"glyph {gname!r}: pixel ({x},{y}) is not aligned to {PIXEL}-unit grid"
            )
        c = x // PIXEL
        r = ROWS_ABOVE_BASELINE - (y // PIXEL)
        if not (0 <= c < COLS and 0 <= r < ROWS_TOTAL):
            raise SystemExit(
                f"glyph {gname!r}: pixel ({x},{y}) → grid ({r},{c}) "
                f"is outside the {ROWS_TOTAL}×{COLS} grid"
            )
        grid[r][c] = "#"
    return ["".join(row) for row in grid]


def emit(data: dict) -> str:
    m = data["metrics"]
    out: list[str] = []
    out.append("; Pixelspace bitmap source — canonical glyph data.")
    out.append("; Format documented in tools/parse_bitmap.py.")
    out.append("; Originally generated by tools/svg_to_bitmap.py from Pixelspace.svg.")
    out.append("; Hand-edits are expected and welcome going forward.")
    out.append("")
    out.append("@meta")
    out.append(f"upem: {m['upem']}")
    out.append(f"ascent: {m['ascent']}")
    out.append(f"descent: {m['descent']}")
    out.append(f"cap-height: {m['cap_height']}")
    out.append(f"x-height: {m['x_height']}")
    out.append(f"default-adv: {m['default_adv']}")
    out.append(f"underline-position: {m['underline_position']}")
    out.append(f"underline-thickness: {m['underline_thickness']}")
    out.append(f"panose: {m['panose']}")
    out.append("")

    if data.get("missing"):
        out.append("; Missing-glyph fallback (rendered for codepoints not in the font).")
        out.append("@glyph .notdef")
        if data["missing"]["adv"] != m["default_adv"]:
            out.append(f"adv: {data['missing']['adv']}")
        out.extend(pixels_to_bitmap(data["missing"]["pixels"], ".notdef"))
        out.append("")

    for g in sorted(data["glyphs"], key=lambda g: ord(g["char"])):
        cp = ord(g["char"])
        out.append(f"@glyph {g['name']}")
        out.append(f"unicode: U+{cp:04X}")
        if g["adv"] != m["default_adv"]:
            out.append(f"adv: {g['adv']}")
        out.extend(pixels_to_bitmap(g["pixels"], g["name"]))
        out.append("")

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    data = parse_svg_font(SRC)
    text = emit(data)
    DST.write_text(text, encoding="utf-8")
    print(
        f"wrote {DST.relative_to(ROOT)} "
        f"({len(text)} bytes, {len(data['glyphs'])} glyphs"
        f"{', + missing-glyph' if data.get('missing') else ''})"
    )
